AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Resources:
  Flow1:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
      Name: copilot-test-contact-flow
      Type: CONTACT_FLOW
      Description: test flow for copilot
      Content: {} # This will be updated by the predeploy.js script
      Tags:
          - Key: testkey
            Value: testValue
  Flow2:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
      Name: copilot-test-contact-flow-2
      Type: CONTACT_FLOW
      Description: test flow for copilot
      Content: {} # This will be updated by the predeploy.js script
      Tags:
          - Key: testkey
            Value: testValue
