AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Resources:
  MyContactFlow:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
      Name: copilot-test-contact-flow
      Type: CONTACT_FLOW
      Description: test flow for copilot
    Content: >
      {
        "Metadata": {
          "entryPointPosition": {
            "x": 50,
            "y": 50
          },
          "snapToGrid": false,
          "ActionMetadata": {
            "entryPoint": {
              "text": "Entry point",
              "visible": false
            }
          }
        },
        "StartAction": "entryPoint",
        "Actions": {
          "entryPoint": {
            "Type": "EntryPoint",
            "Parameters": {},
            "Transitions": {
              "NextAction": "invokeLambdaFunction",
              "Errors": [],
              "Conditions": []
            }
          },
          "invokeLambdaFunction": {
            "Type": "InvokeLambdaFunction",
            "Parameters": {
              "FunctionArn": "arn:aws:lambda:us-east-1:123456789012:function:my-function"
            },
            "Transitions": {
              "NextAction": "endFlow",
              "Errors": [],
              "Conditions": []
            }
          },
          "endFlow": {
            "Type": "EndFlow",
            "Parameters": {},
            "Transitions": {}
          }
        }
      }
