AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application.

Resources:
  Flow1:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
      Name: copilot-test-contact-flow
      Type: CONTACT_FLOW
      Description: test flow for copilot
      Content: |
        {
          "Version": "2019-10-30",
          "StartAction": "Play",
          "Metadata": {
              "entryPointPosition": {
                  "x": 40,
                  "y": 40
              },
              "ActionMetadata": {
                  "5a9f1dfb-4891-4790-87ea-c8511192d959": {
                      "position": {
                          "x": 570.4,
                          "y": 259.2
                      }
                  },
                  "Play": {
                      "position": {
                          "x": 148,
                          "y": 172.8
                      },
                      "isFriendlyName": true,
                      "parameters": {
                          "PromptId": {
                              "displayName": "Beep.wav"
                          }
                      },
                      "promptName": "Beep.wav"
                  }
              },
              "Annotations": [],
              "name": "Copilot-test-flow",
              "description": "",
              "type": "contactFlow",
              "status": "published",
              "hash": {}
          },
          "Actions": [
              {
                  "Parameters": {},
                  "Identifier": "5a9f1dfb-4891-4790-87ea-c8511192d959",
                  "Type": "DisconnectParticipant",
                  "Transitions": {}
              },
              {
                  "Parameters": {
                      "PromptId": "arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e/prompt/adf5e4e6-65ee-4008-adb7-4a34c77accb9"
                  },
                  "Identifier": "Play",
                  "Type": "MessageParticipant",
                  "Transitions": {
                      "NextAction": "5a9f1dfb-4891-4790-87ea-c8511192d959",
                      "Errors": [
                          {
                              "NextAction": "5a9f1dfb-4891-4790-87ea-c8511192d959",
                              "ErrorType": "NoMatchingError"
                          }
                      ]
                  }
              }
          ]
        }
      Tags:
          - Key: testkey
            Value: testValue
  Flow2:
    Type: AWS::Connect::ContactFlow
    Properties:
      InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
      Name: copilot-test-contact-flow-2
      Type: CONTACT_FLOW
      Description: test flow for copilot
      Content: |
        {
            "Version": "2019-10-30",
            "StartAction": "6f40a3e9-ff2d-4255-b458-5e0f71ae7942",
            "Metadata": {
                "entryPointPosition": {
                    "x": 40,
                    "y": 40
                },
                "ActionMetadata": {
                    "81013a74-5e01-4a05-ba6d-513dd3c54297": {
                        "position": {
                            "x": 388.8,
                            "y": 58.4
                        }
                    },
                    "6f40a3e9-ff2d-4255-b458-5e0f71ae7942": {
                        "position": {
                            "x": 164,
                            "y": 39.2
                        },
                        "parameters": {
                            "PromptId": {
                                "displayName": "Beep.wav"
                            }
                        },
                        "promptName": "Beep.wav"
                    }
                },
                "Annotations": [],
                "name": "Copilot-test-flow-2",
                "description": "",
                "type": "contactFlow",
                "status": "published",
                "hash": {}
            },
            "Actions": [
                {
                    "Parameters": {},
                    "Identifier": "81013a74-5e01-4a05-ba6d-513dd3c54297",
                    "Type": "DisconnectParticipant",
                    "Transitions": {}
                },
                {
                    "Parameters": {
                        "PromptId": "arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e/prompt/adf5e4e6-65ee-4008-adb7-4a34c77accb9"
                    },
                    "Identifier": "6f40a3e9-ff2d-4255-b458-5e0f71ae7942",
                    "Type": "MessageParticipant",
                    "Transitions": {
                        "NextAction": "81013a74-5e01-4a05-ba6d-513dd3c54297",
                        "Errors": [
                            {
                                "NextAction": "81013a74-5e01-4a05-ba6d-513dd3c54297",
                                "ErrorType": "NoMatchingError"
                            }
                        ]
                    }
                }
            ]
        }
      Tags:
          - Key: testkey
            Value: testValue
  Flow3:
    Type: AWS::Connect::ContactFlow
    Properties:
        InstanceArn: arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e
        Name: copilot-test-contact-flow-3
        Type: CONTACT_FLOW
        Description: test flow for copilot
        Content:
            {
                "Version": "2019-10-30",
                "StartAction": "777e1eb3-b581-42db-a3e1-f6ddd36cb92e",
                "Metadata": {
                    "entryPointPosition": {
                        "x": 14.4,
                        "y": 18.4
                    },
                    "ActionMetadata": {
                        "777e1eb3-b581-42db-a3e1-f6ddd36cb92e": {
                            "position": {
                                "x": 216,
                                "y": 21.6
                            }
                        },
                        "cffe8ffb-cd78-48cf-ad03-1cd12406a4e1": {
                            "position": {
                                "x": 522.4,
                                "y": 261.6
                            }
                        },
                        "24e3fc07-7966-495d-a297-ce58218543dc": {
                            "position": {
                                "x": 801.6,
                                "y": 429.6
                            }
                        },
                        "d29fb27c-c0d1-4a13-ab1c-e0b59081c39b": {
                            "position": {
                                "x": 476.8,
                                "y": 14.4
                            }
                        },
                        "6add197c-b043-4131-a4fc-aafd87a6a1f7": {
                            "position": {
                                "x": 194.4,
                                "y": 248.8
                            },
                            "parameters": {
                                "QueueId": {
                                    "displayName": "BasicQueue"
                                }
                            },
                            "queue": {
                                "text": "BasicQueue"
                            }
                        }
                    },
                    "Annotations": [],
                    "name": "Basic Chat Flow",
                    "description": "",
                    "type": "contactFlow",
                    "status": "published",
                    "hash": {}
                },
                "Actions": [
                    {
                        "Parameters": {
                            "FlowLoggingBehavior": "Enabled"
                        },
                        "Identifier": "777e1eb3-b581-42db-a3e1-f6ddd36cb92e",
                        "Type": "UpdateFlowLoggingBehavior",
                        "Transitions": {
                            "NextAction": "d29fb27c-c0d1-4a13-ab1c-e0b59081c39b"
                        }
                    },
                    {
                        "Parameters": {},
                        "Identifier": "cffe8ffb-cd78-48cf-ad03-1cd12406a4e1",
                        "Type": "TransferContactToQueue",
                        "Transitions": {
                            "NextAction": "24e3fc07-7966-495d-a297-ce58218543dc",
                            "Errors": [
                                {
                                    "NextAction": "24e3fc07-7966-495d-a297-ce58218543dc",
                                    "ErrorType": "QueueAtCapacity"
                                },
                                {
                                    "NextAction": "24e3fc07-7966-495d-a297-ce58218543dc",
                                    "ErrorType": "NoMatchingError"
                                }
                            ]
                        }
                    },
                    {
                        "Parameters": {},
                        "Identifier": "24e3fc07-7966-495d-a297-ce58218543dc",
                        "Type": "DisconnectParticipant",
                        "Transitions": {}
                    },
                    {
                        "Parameters": {
                            "Text": "Transferring to Agent Hema"
                        },
                        "Identifier": "d29fb27c-c0d1-4a13-ab1c-e0b59081c39b",
                        "Type": "MessageParticipant",
                        "Transitions": {
                            "NextAction": "6add197c-b043-4131-a4fc-aafd87a6a1f7",
                            "Errors": [
                                {
                                    "NextAction": "6add197c-b043-4131-a4fc-aafd87a6a1f7",
                                    "ErrorType": "NoMatchingError"
                                }
                            ]
                        }
                    },
                    {
                        "Parameters": {
                            "QueueId": "arn:aws:connect:us-east-1:750344256621:instance/4bbee21d-72b8-442b-af39-dce4128ca77e/queue/249daaf1-4883-430a-bba5-054fc7e6e10c"
                        },
                        "Identifier": "6add197c-b043-4131-a4fc-aafd87a6a1f7",
                        "Type": "UpdateContactTargetQueue",
                        "Transitions": {
                            "NextAction": "cffe8ffb-cd78-48cf-ad03-1cd12406a4e1",
                            "Errors": [
                                {
                                    "NextAction": "24e3fc07-7966-495d-a297-ce58218543dc",
                                    "ErrorType": "NoMatchingError"
                                }
                            ]
                        }
                    }
                ]
            }
